export const PORTFOLIO_DATA = {
  projects: [
    { title: "AutoTune-SQL", desc: "AI SQL Optimizer", img: "/src/assets/ProjectsImages/AutoTune-SQL.png", github: "https://github.com/abeerpathela/AutoTune-SQL", live: "https://autotune-sql.in", tech: ["React", "Node", "OpenAI"] },
    { title: "SimAPI", desc: "SMS Gateway", img: "/src/assets/ProjectsImages/SimAPI.png", github: "https://github.com/abeerpathela/SimAPI", live: "https://sim-api-one.vercel.app", tech: ["Flutter", "Node", "MongoDB"] },
    { title: "Genetic Guardrail", desc: "Genomic Safety", img: "/src/assets/ProjectsImages/GeneticGuardrail.png", github: "https://github.com/abeerpathela/GeneticGuardrail", live: "", tech: ["Node", "Python"] },
    { title: "NullPrompt", desc: "AI Privacy Extension", img: "/src/assets/ProjectsImages/NullPrompt.png", github: "https://github.com/abeerpathela/NullPrompt", live: "", tech: ["JavaScript", "Privacy"] },
    { title: "Razorpay Clone", desc: "UI Recreation", img: "/src/assets/ProjectsImages/RazorpayClone.png", github: "https://github.com/abeerpathela/Razorpay-Clone", live: "https://razorpay-clone-chi-eight.vercel.app", tech: ["Tailwind", "JS"] },
    { title: "Jal Sahayak AI", desc: "Water Complaint AI", img: "/src/assets/ProjectsImages/JalSahayakAI.png", github: "https://github.com/abeerpathela/Jal-Sahayak-AI", live: "https://jal-sahayak-ai.vercel.app", tech: ["MERN", "OpenAI"] },
    { title: "CodeFixo", desc: "AI Code Review", img: "/src/assets/ProjectsImages/CodeFixo.png", github: "https://github.com/abeerpathela/CodeFixo", live: "https://code-fixo.vercel.app", tech: ["React", "Node"] },
    { title: "AiTextra", desc: "Offline SMS Bot", img: "/src/assets/ProjectsImages/AiTextra.png", github: "https://github.com/abeerpathela/AiTextra", live: "", tech: ["Twilio", "OpenAI"] },
    { title: "BrainBuster", desc: "Interactive Quiz", img: "/src/assets/ProjectsImages/BrainBuster.png", github: "https://github.com/abeerpathela/BrainBuster", live: "https://brain-buster-lac.vercel.app", tech: ["React", "JS"] },
  ],
  participations: [
    { title: "HackIndia 2026", img: "/src/assets/Participations/HackIndia2026.jpeg", link: "https://www.linkedin.com/posts/abeer-pathela-240001313_hackindia2026-hackathon-ai-activity-7455283772058509313-bbkz" },
    { title: "BuildX", img: "/src/assets/Participations/BuildX.png", link: "https://www.linkedin.com/posts/abeer-pathela-240001313_hackathon-buildx-innovation-activity-7462754885097295872-mClT" },
    { title: "Chitkaraverse", img: "/src/assets/Participations/Chitkaraverse.png", link: "https://www.linkedin.com/posts/avinash-guleria-a18553324_chitkaraverse2026-hackathon-aiimpact-ugcPost-7447265770331623424-swhG" },
    { title: "NumPy Physics", img: "/src/assets/Participations/Numpy.png", link: "https://www.linkedin.com/posts/abeer-pathela-240001313_teamwork-physics-gamedevelopment-activity-7263471895314886656-UhVd" },
  ],
  techStack: [
    { name: "React",      icon: "SiReact",          color: "#61DAFB" },
    { name: "Next.js",    icon: "SiNextdotjs",      color: "#FFFFFF" },
    { name: "TypeScript", icon: "SiTypescript",     color: "#3178C6" },
    { name: "Node.js",    icon: "SiNodedotjs",      color: "#5FA04E" },
    { name: "Express",    icon: "SiExpress",        color: "#FFFFFF" },
    { name: "MongoDB",    icon: "SiMongodb",        color: "#47A248" },
    { name: "PostgreSQL", icon: "SiPostgresql",     color: "#4169E1" },
    { name: "Python",     icon: "SiPython",         color: "#FFD43B" },
    { name: "Flutter",    icon: "SiFlutter",        color: "#02569B" },
    { name: "Tailwind",   icon: "SiTailwindcss",    color: "#38BDF8" },
    { name: "Three.js",   icon: "SiThreedotjs",     color: "#FFFFFF" },
    { name: "GSAP",       icon: "SiGreensock",      color: "#88CE02" },
    { name: "OpenAI",     icon: "SiOpenai",         color: "#10A37F" },
    { name: "Docker",     icon: "SiDocker",         color: "#2496ED" },
    { name: "AWS",        icon: "SiAmazonwebservices", color: "#FF9900" },
    { name: "Vercel",     icon: "SiVercel",         color: "#FFFFFF" },
    { name: "Git",        icon: "SiGit",            color: "#F05032" },
    { name: "Redis",      icon: "SiRedis",          color: "#FF4438" },
    { name: "GraphQL",    icon: "SiGraphql",        color: "#E10098" },
    { name: "Firebase",   icon: "SiFirebase",       color: "#FFCA28" },
    { name: "Supabase",   icon: "SiSupabase",       color: "#3ECF8E" },
    { name: "Vite",       icon: "SiVite",           color: "#FFC21A" },
  ],
  stats: { cgpa: "9.58", leetcode: "100+", resume: "/src/assets/Abeer_Pathela_Resume.pdf" },
  sectors: ["PROJECTS NEBULA", "PARTICIPATIONS GALLERY", "TECH GALAXY", "ACHIEVEMENT CORE", "CONTACT CHANNEL"],
};

export const STATION_SPACING = 50;